#!/bin/bash
#
# This file is released under terms of BSD license
# See LICENSE file for more information
#
# git pre-commit hooks that run shellcheck and license check.
# - the commit will abort if the shellcheck does not pass.
# - the commit will abort if files are missing the license information.
#
# author: clementval
#

GIT_ROOT=$(git rev-parse --show-toplevel)

# Run author checker
if ! "${GIT_ROOT}"/scripts/check_author; then
  echo "One of your source code files does not have @author information!"
  exit 1
fi

# Run license checker
if ! "${GIT_ROOT}"/scripts/check_license; then
  echo "One of your source code files does not have license information!"
  exit 1
fi

# Run shellcheck
cd "${GIT_ROOT}"/scripts || exit 1
if ! ./run.shellcheck; then
  echo "One of your bash script does not comply with shellcheck!"
  exit 1
fi
