#!/bin/bash
#
# This file is released under terms of BSD license
# See LICENSE file for more information
#
# git pre-commit hooks that run shellcheck and license check.
# - the commit will abort if the shellcheck does not pass.
# - the commit will abort if files are missing the license information.
#
# author: clementval
#

GIT_ROOT=$(git rev-parse --show-toplevel)

if ! python "${GIT_ROOT}"/scripts/check_author_license.py; then
  exit 1
fi

# Run shellcheck
cd "${GIT_ROOT}"/scripts || exit 1
if ! ./run.shellcheck; then
  echo "One of your bash script does not comply with shellcheck!"
  exit 1
fi
