#!/bin/bash
#
# This file is released under terms of BSD license
# See LICENSE file for more information
#
# Helper script check author is present in all java code files.
# Must be run from the root directory.
#
# author: clementval
#
if [ ! -f LICENSE ] ; then
    echo "The script has to be executed from the root directory ./script/check_author"
    exit 1
fi

license_error=0
while IFS= read -r -d '' file
do
  if ! grep -q "@author" "${file}" ; then
    let license_error++
    echo "${file} has no @author javadoc information."
  fi
done < <(find ./cx2t -path ./cx2t/src/claw/wani/language/parser -prune -o -iname "*.java" -print0)

if [[ license_error -ne 0 ]]; then
  echo "${license_error} files without @author javadoc information!"
  exit 2
fi
