#!/bin/bash
#
# This file is released under terms of BSD license
# See LICENSE file for more information
#
# Helper script check license is present in all source code files.
# Must be run from the root directory.
#
# author: clementval
#
if [ ! -f LICENSE ] ; then
    echo "The script has to be executed from the root directory ./script/check_license"
    exit 1
fi

license_error=0
while IFS= read -r -d '' file
do
  if ! grep -i -q "license" "${file}" ; then
    (( license_error++ ))
    echo "${file} has no license information."
  fi
done < <(find . -path ./build/omni-compiler -prune -o -iname "*.java" -print0)

while IFS= read -r -d '' file
do
  if ! grep -i -q "license" "${file}" ; then
    (( license_error++ ))
    echo "${file} has no license information."
  fi
done < <(find . ! -path "*/__omni_tmp__/*" -a ! -path "./build/*" \
  -a ! -path "*/omni-compiler/*" -a ! -path "*/documentation/*" \
  -type f -name "*.f90"  -a ! -iname "transformed_*" \
  -a ! -iname "reference*" -print0)

if [[ license_error -ne 0 ]]; then
  echo "${license_error} files without license information!"
  exit 2
fi
