#!/bin/bash
#
# This file is released under terms of BSD license
# See LICENSE file for more information
#
# Helper script tp update omni to the latest version.
# Must be run from the root directory.
#
# author: clementval
#
if [ ! -f LICENSE ] ; then
    echo "The script has to be executed from the root directory ./script/update_omni"
    exit 1
fi

CRT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

SUBMODULE_PATH="omni-compiler"

git submodule update --remote "${SUBMODULE_PATH}" || exit 1

cd "${SUBMODULE_PATH}" || exit 1

CRT_HASH=$(git rev-parse HEAD)
CRT_HASH_SHORT=$(git rev-parse --short HEAD)

cd ..  || exit 1

if [[ "${CRT_BRANCH}" == "master" ]]; then
  echo "Current branch is master. Creating branch omni/${CRT_HASH_SHORT}"
  git checkout -b "omni/${CRT_HASH_SHORT}" || exit 1
fi

git add "${SUBMODULE_PATH}" || exit 1
git commit -m "Update OMNI Compiler to ${CRT_HASH}" || exit 1

echo "OMNI Compiler submodule updated to ${CRT_HASH}"
echo "PR text:"
echo ""
echo "Update OMNI Compiler submodule to omni-compiler/xcodeml-tools@${CRT_HASH}"
