name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for making us aware of an issue with this repository. We will have a look at it as soon as possible.'
        pr-message: 'Thank you for making a pull request on this repository and contributing to open-source. We will have a look at it as soon as possible.'
