# 

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Git submodule
        run: |
          git submodule init
          git submodule update

      - name: Check author
        run: python "./scripts/check_author_license.py"
        
      - name: Check shellcheck
        run: |
          cd scripts
          ./run.shellcheck
          cd ..
      
      - name: Build + test
        run: | 
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=../install ..
          make -j
          make install
          export CLAW_HOME=../install
          export OMNI_HOME=../install
          make run-tests
